name = "katlen-admin"
main = "worker.js"
compatibility_date = "2026-08-01"

# =========================================================
# CLOUDFLARE KV
# =========================================================

[[kv_namespaces]]
binding = "SITE_KV"
id = "9029bb29b25b4c899f3a25e63f7fd3bb"


# =========================================================
# VARIÁVEIS / SECRETS
# =========================================================
#
# NÃO coloque SESSION_SECRET nem SETUP_TOKEN aqui.
#
# Eles serão configurados como Secrets no Cloudflare:
#
# SESSION_SECRET
# SETUP_TOKEN
#
# =========================================================
